---
# Dict for category names:
title:
  '0': "Last Torrent"
  '1': "Catégorie Vidéo"
  '2': "Catégorie Audio"
  '3': "Catégorie Application"
  '4': "Catégorie Ebooks"
  '5': "Catégorie Jeu-Vidéo"
  '6': "Catégorie Formation"
  '7': "Catégorie XXX"
  '9': "SubCatégorie Film"
  '10': "SubCatégorie Série"
  '11': "SubCatégorie Film Animation"
  '12': "SubCatégorie Série Animation"
  '13': "SubCatégorie Documentaire"
  '14': "SubCatégorie Emission TV"
  '15': "SubCatégorie Spectacle & Concert"
  '16': "SubCatégorie Sport"
  '17': "SubCatégorie Karaoké Vidéo"
  '18': "SubCatégorie Karaoké"
  '19': "On The Cloud"
  '20': "SubCatégorie Musique"
  '21': "SubCatégorie Podcast"
  '22': "SubCatégorie Sample"
  '23': "SubCatégorie Ebook Audio"
  '24': "SubCatégorie BD"
  '25': "SubCatégorie Comic"
  '26': "SubCatégorie Manga"
  '27': "SubCatégorie Livre"
  '28': "SubCatégorie Presse"
  '29': "SubCatégorie Application Linux"
  '30': "SubCatégorie Application Windows"
  '31': "SubCatégorie Application Mac"
  '32': "On The Cloud"
  '33': "On The Cloud"
  '34': "SubCatégorie Application Smartphone/Tablette"
  '35': "SubCatégorie GPS"
  '36': "SubCatégorie Jeux Linux"
